# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/max_temperature_donetsk',
                'doc_host': 'https://slavam.github.io',
                'git_url': 'https://github.com/slavam/max_temperature_donetsk',
                'lib_path': 'max_temperature_donetsk'},
  'syms': {'max_temperature_donetsk.core': {'max_temperature_donetsk.core.foo': ('core.html#foo', 'max_temperature_donetsk/core.py')}}}
